### ISSUE TITLE
5 Botton dint work

### ISSUE THREAD

**Issue by lucasadu** [Ashung/Sketch_Swatches#11]
Hey bro,

1st of all i want to say thank you for the swatches, i really appreciate your effort.

My issue is, when i click "apply to..." all the 5 button on right bottom side it does not work.
for your info im using Sketch ver.41.2.

I hope you can guide me on how to solve this issue.

Thanks.

<img width="153" alt="screen shot 2017-04-17 at 3 28 14 pm" src="https://cloud.githubusercontent.com/assets/27669838/25082299/81f2756e-2382-11e7-8fd8-bb8657912ecd.png">

**Comment by Ashung** [comment]
@lucasedu, download the new version of Swatches, but strong suggest you update to latest version of Sketch, a lot of plugins are no compatible with old version.

**Comment by lucasadu** [comment]
@Ashung ,alright bro, thanks for the updated swatches, appreciate your plugin.
