### ISSUE TITLE
Custom swatches?

### ISSUE THREAD

**Issue by xandermarsh** [Ashung/Sketch_Swatches#2]
Any plans to update this with custom swatches for the user?

**Comment by godyj** [comment]
Great plugin and loving it. Please provide functionality for custom swatches.

**Comment by Ashung** [comment]
You can use system color panel for custom swatches, click menu "View" - "Show Colors".

http://www.robinwood.com/Catalog/Technical/OtherTuts/MacColorPicker/MacColorPicker.html

**Comment by xandermarsh** [comment]
Yeah, I (we?) know. It's not the most ideal workflow, you also can't easily name them or create groupings. It would be a HUGE benefit if you added it in.
