### ISSUE TITLE
where do i find it ?

### ISSUE THREAD

**Issue by CyrusZei** [Ashung/Sketch_Swatches#5]
hi,

Where do it find this after I installed it ? Maybe you could add this in the ReadMe.md file ?

**Comment by osadasami** [comment]
Plugins -> Swatches -> Swatches
https://cloud.mail.ru/public/DAHv/3mgi7w87Y

**Comment by CyrusZei** [comment]
Something must have happend with my installation since I downloaded it and double clicked on it and it says "you already have it installed" when i look at the sketch toolbox it says I can install it so I did and now it works. strange, but thx for the help
